/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/bathing` | `/bathing`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/medical` | `/medical`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/food` | `/food`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/setting` | `/setting`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/tasks` | `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/tasks/medical` | `/tasks/medical`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/tasks/[id]` | `/tasks/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/bathing` | `/bathing`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/medical` | `/medical`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/food` | `/food`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/setting` | `/setting`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/tasks` | `/tasks`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/tasks/medical` | `/tasks/medical`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/tasks/[id]` | `/tasks/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/bathing${`?${string}` | `#${string}` | ''}` | `/bathing${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/medical${`?${string}` | `#${string}` | ''}` | `/medical${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/food${`?${string}` | `#${string}` | ''}` | `/food${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/setting${`?${string}` | `#${string}` | ''}` | `/setting${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/tasks${`?${string}` | `#${string}` | ''}` | `/tasks${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/tasks/medical${`?${string}` | `#${string}` | ''}` | `/tasks/medical${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/bathing` | `/bathing`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/medical` | `/medical`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/food` | `/food`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/setting` | `/setting`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/tasks` | `/tasks`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/tasks/medical` | `/tasks/medical`; params?: Router.UnknownInputParams; } | `${'/(dashboard)'}/tasks/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/tasks/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(dashboard)'}/tasks/[id]` | `/tasks/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
